### ISSUE TITLE
How to Run The Project in Windows?

### ISSUE THREAD

**Issue by icandura** [ianrenton/disqus-to-hashover#1]
I import it to Eclipse but it couldn't work, How to run the project?

**Comment by ianrenton** [comment]
I haven't tried it using Eclipse, only in NetBeans - what error do you get?

**Comment by icandura** [comment]
I think I need install JAXB first, I completed it by ANT, the error is
`BUILD FAILED
disqus-to-hashover-master\nbproject\xml
_binding_build.xml:6: typedef class com.sun.tools.xjc.XJCTask cannot be found
 using the classloader AntClassLoader[]`

**Comment by ianrenton** [comment]
Ah, right. I used NetBeans' built-in JAXB plugin to transform the schema into Java code, so if Eclipse has its own JAXB plugin that you can enable for the project, that might be the quickest way to fix it. Otherwise you can download the JAXB Ant JAR(s) from the web and add them as compile time dependencies.

**Comment by icandura** [comment]
It Wroks! Thank you~
